### ISSUE TITLE
Cannot test Request because a meaningful Request object cannot be created manually

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/web#23]
Mongoose being a private header+source makes it difficult to test Request methods because we cannot fully build a request: we don't have access to the `struct mg_connection` definition.

For example the following would be a desirable test:

```
corto_void _test_WebTestSuite_tc_getQueryParams(
    test_WebTestSuite this)
{
/* $begin(test/WebTestSuite/tc_getQueryParams) */
    struct mg_connection conn = {
        "GET",
        "localhost",
        "1.1",
        "query=what+is+the+meaning+of+life"
    };
    server_HTTP_Request request = {
        "localhost",
        server_GET,
        (corto_word)&conn,
        FALSE
    };
    rb_tree params = server_HTTP_Request_getGetForm(request);
    test_assert(params != NULL);
    test_assert(corto_rbtreeSize(params) == 1);
    corto_rbtreeFree(params);
/* $end */
}
```

However, we cannot create the connection object because `#include "mongoose.h"` would be needed.

A potentially clean solution could be separating mongoose from corto/web so that it can be consumed both by corto/web and by corto/web's test.

Another solution, but potentially a lot more manual, is to include "helper" functions in corto/web so that they can we can build requests to test request methods. This could require basically rewriting the mg_connection object, which seems undesirable.

**Comment by SanderMertens** [comment]
The mongoose connection is wrapped by the HTTP_Request. Tests should be written on top of HTTP_Request, not the mongoose headers. The framework is built in a way so that it can support different HTTP implementations (as well as cgi/fastcgi). If you write your testcases without dependencies on the underlying implementation, you'll be able to reuse the testcases for different HTTP implementations.

**Comment by jleeothon** [comment]
I'll agree that we should test on top of HTTP_Request, but we cannot create a meaningful instance of HTTP_Request from outside the /corto/web/server package.

Another option:
Add all significant members of `mg_connection` as members of `Request`

This way we can create the request from outside. For example:

struct Request::
    uri: string  // already there
    method: HTTP::Method // already there
    file: bool // already there
    body: string // new, only for POST
    query: string // new, only for GET

**Comment by jleeothon** [comment]
Server can be right now tested in conjunction with the native client. If the need of (isolated) unit testing arises naturally, then we'll consider looking at this issue again.
